name: RealBiomeConditon
version: ${project.version}
authors: [ StrangeOne101 ]
description: Adds a real biome condition to MythicMobs

main: com.strangeone101.realbiomecondition.Plugin
api-version: 1.18

depend: [ MythicMobs ]
